-- Unit preference per client (display-only; canonical storage stays kg/cm)
create type unit_preference as enum ('METRIC', 'IMPERIAL');

alter table public.clients
  add column unit_preference unit_preference not null default 'METRIC';

-- Mark whether a target row was generated by the auto-adjustment system,
-- and why, so coaches can see the reasoning in the UI.
alter table public.targets
  add column is_auto_generated boolean not null default false,
  add column adjustment_reason text;

-- New notification type for auto-adjusted targets
alter type notification_type add value if not exists 'TARGET_AUTO_ADJUSTED';
